# Generated by Django 2.2.7 on 2020-01-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30, verbose_name='department which request a job')),
                ('supervisor', models.CharField(max_length=20, verbose_name='Pincipal Investigator')),
                ('project', models.CharField(max_length=100, verbose_name='name of the project where this job is included')),
            ],
        ),
    ]
