# Generated by Django 2.2.7 on 2019-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=5)),
                ('project', models.TextField(max_length=200)),
                ('priority_status', models.CharField(max_length=5)),
                ('pi', models.CharField(max_length=20)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
