# Generated by Django 2.2.7 on 2020-01-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='name of the person who contact')),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=5, verbose_name='owrk position of the eam member')),
                ('inquiry', models.TextField(max_length=200, verbose_name='few lines of resume')),
            ],
        ),
    ]
