# Generated by Django 2.2.7 on 2020-01-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, verbose_name='title for the request job')),
                ('priority_status', models.CharField(choices=[('high', 'high'), ('mid', 'mid'), ('low', 'low'), ('none', 'none')], default='none', max_length=5)),
                ('subject', models.CharField(max_length=200, verbose_name='short summary of the project subject')),
                ('research_question', models.CharField(max_length=200)),
                ('sample_number', models.IntegerField()),
                ('expectations', models.CharField(max_length=200, verbose_name='what do you expect to get form this analysis')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('data_type', models.CharField(max_length=10, verbose_name='DNA, RNA, miRNAs, scRNA others')),
                ('alignment', models.BooleanField()),
                ('annotation', models.BooleanField()),
                ('de_analysis', models.CharField(max_length=100)),
                ('other_analysis', models.CharField(max_length=200)),
                ('detailed_question', models.TextField()),
                ('detailed_summary', models.TextField()),
                ('other_info', models.TextField(blank=True)),
                ('is_payed', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
