# Generated by Django 2.2.7 on 2019-12-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('data_type', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('is_priority', models.CharField(max_length=10)),
            ],
        ),
    ]
