# Generated by Django 2.2.7 on 2020-01-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('priority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_priority', models.BooleanField()),
                ('subject', models.CharField(max_length=200, verbose_name='short summary of the project subject')),
                ('research_question', models.CharField(max_length=200)),
                ('sample_number', models.IntegerField()),
                ('expectations', models.CharField(max_length=200, verbose_name='what do you expect to get form this analysis')),
                ('deadline', models.DateTimeField()),
                ('data_type', models.CharField(max_length=10, verbose_name='DNA, RNA, miRNAs, scRNA others')),
                ('alignment', models.BooleanField()),
                ('annotation', models.BooleanField()),
                ('de_analysis', models.CharField(max_length=100)),
                ('other_analysis', models.CharField(max_length=200)),
                ('detailed_question', models.TextField()),
                ('detailed_summary', models.TextField()),
                ('other_info', models.TextField(blank=True)),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priority.Clients')),
            ],
        ),
    ]
