# Generated by Django 2.2.7 on 2020-01-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('requestform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
