# Generated by Django 2.2.7 on 2020-01-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestform', '0002_jobs_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='is_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priority.Clients'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_name',
            field=models.CharField(max_length=30, verbose_name='title for the request job'),
        ),
    ]
