# Generated by Django 2.2.7 on 2019-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='images')),
                ('jobtitle', models.CharField(blank=True, max_length=10)),
                ('resume', models.TextField(max_length=200)),
                ('experience', models.TextField(max_length=120)),
                ('skills', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
