# Generated by Django 2.2.7 on 2020-01-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('position', models.CharField(blank=True, max_length=5, null=True)),
                ('resume', models.TextField(max_length=200)),
                ('experience', models.TextField(max_length=120)),
                ('skills', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('jobstatus_update', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
