# Generated by Django 2.2.7 on 2020-01-21 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='name of the team member')),
                ('position', models.CharField(max_length=5, verbose_name='owrk position of the eam member')),
                ('resume', models.TextField(max_length=200, verbose_name='few lines of resume')),
                ('experience', models.TextField(max_length=120, verbose_name='experience in data analysis')),
                ('skills', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobstatus_update', models.TextField(max_length=300)),
            ],
        ),
    ]
