# Generated by Django 2.2.7 on 2020-01-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
        ('priority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priority.Clients'),
        ),
    ]
